EfficientNetV1 refactor First PR
rapidrabbit76/Classification-For-Everyone pull request #11
Opened 2022-02-25 06:02 UTC by zkdlfrlwl2

optimzer를 어떻게 관리할지 생각해봐야겠는데. SGD & RMSProp & ADAM 이런거 미리 명시해놓고 arg로 만들어야하나

2022-02-25 09:28 UTC, rapidrabbit76 commented
Optimizer 여러개 쓰게 하고 싶은데 그렇게하려면 args 너무 복잡해지지 않을까? 
좋은 방법있으면 소개좀 해줘 

모델 안에 LitModel을 하나 더 보관하는게 좋은 방법인지 모르겠네 지금보니깐 

학습하는 로직이 거의 비슷해서 중복이 엄청 나오던데 
그 중복을 전부 없에는게 좋을지 아니면 읽을수있게 놔두는게 좋을지 고민중임 ..

2022-02-25 09:45 UTC, zkdlfrlwl2 commented
@rapidrabbit76 아예 LitModel 부모 클래스 하나 만들어서 그거 상속 받아서 self.model만 다르게 입력 받고 def configure_optimizers(self) 얘만 좀 커스텀 하면 중복 없앨 수 있지 않을까 ?

2022-02-25 09:49 UTC, rapidrabbit76 commented
ㅇㅇ 중복은 없앨수 있는데 그게 좋은코드일까 싶어서 ... 너무 추상화시키려는게 아닐까 싶어서 

고민중 ㅋㅋㅋㅋ

어떻게 생각함?

2022-02-25 10:19 UTC, zkdlfrlwl2 commented
코드가 길어지더라도 main.py에 LitModel 넣는 것도 나쁘지는 않을 듯 ? main.py에 LitModel 집어넣으면 init weights는 다시 models.py로 빼고

2022-02-27 10:26 UTC, rapidrabbit76 commented
> 

ㅇㅇ 무슨 말인지 알겠음 난 그게 좋을까 의문이라서 안하려고 했는데 괜찮아 보이면 노션 칸반하나 만들어줘 한번 고민해 보자

2022-02-27 10:51 UTC, rapidrabbit76 requested changes

2022-02-27 10:51 UTC, rapidrabbit76 commented on models/EfficientNetV1/lightning_model.py
> +        """
주석 안쓸꺼면 삭제

2022-02-27 10:51 UTC, rapidrabbit76 commented on models/EfficientNetV1/lightning_model.py
> +            'scheduler': ReduceLROnPlateau(
이부분을 어떻게 잘 ... 고치지 ㅠㅠ

2022-02-27 10:51 UTC, rapidrabbit76 commented on models/EfficientNetV1/models.py
> +def efficientnet_b0(
Camel Case 로 통일 부탁

2022-02-27 10:51 UTC, rapidrabbit76 commented on main.py
> +    "EFFICIENTNETV1": LitEfficientNet,
아 이거 음 대소문자 구분 없이 하려고 했는데 정확하게 하자

2022-02-27 10:51 UTC, rapidrabbit76 commented on main.py
> +    "EFFICIENTNETV1": LitEfficientNet,
`"EfficientNetv1": LitEfficientNet `

2022-02-27 10:51 UTC, rapidrabbit76 commented on models/MNASNet/blocks.py
> +        if act == 'ReLU':
아하 이방법을 썼구만

2022-02-27 10:51 UTC, rapidrabbit76 commented on models/MNASNet/blocks.py
> +        else:
else는 가능한 없에고

2022-02-27 10:51 UTC, rapidrabbit76 commented on models/MNASNet/models.py
> +def mnasnet1_0(
이거 전부 카멜 케이스로 변경 부탁

2022-02-27 23:53 UTC, zkdlfrlwl2 commented on main.py
> +    "EFFICIENTNETV1": LitEfficientNet,
이렇게 하니까 upper case error 뱉던데 ?

2022-02-27 23:57 UTC, zkdlfrlwl2 commented on models/MNASNet/blocks.py
> +        if act == 'ReLU':
ㅇㅇ 난 이게 좋더라

2022-02-28 00:18 UTC, zkdlfrlwl2 commented on models/MNASNet/models.py
> +def mnasnet1_0(
upper or lower 둘 중 어느걸로 ?

2022-02-28 02:08 UTC, zkdlfrlwl2 commented on main.py
> +    "EFFICIENTNETV1": LitEfficientNet,
![image](https://user-images.githubusercontent.com/92927837/155912599-3be5d15b-0396-4c50-be72-afa616b960f2.png)

2022-03-03 16:32 UTC, rapidrabbit76 commented
> 
@zkdlfrlwl2 
ㅇㅇ 고민했는데 이렇게 하는게 좋을 거 같네 지금 구조는 중복이 너무 많다 
LitBase 하나 만들어서 상속 받는 구조로 만들자 
모델 리펙토링 끝나면 내 쪽에서 일괄적으로 작업할 게요!

2022-03-04 05:27 UTC, rapidrabbit76 commented
pull 한번 하고 적용해서 다시 PR 날려줘 지금 꺼는 close 할게요.

2022-03-04 05:27 UTC, closed without merging