PR
rapidrabbit76/Classification-For-Everyone pull request #16
Opened 2022-03-04 10:15 UTC by zkdlfrlwl2

[init: first commit about yslee refactor branch](https://github.com/rapidrabbit76/Classification-For-Everyone/commit/56c1cf75ad5860f9531e2892d246f2845f24dfee)

오늘자 위 commit 부터 보면 됨.

니 refactor branch를 그냥 clone 해서 내가 작업한 모델만 하나씩 옮기면서 commit 했다. pull 댕겨올라니까 merge conflict 떠서.. 

근데 이렇게 해도 auto merge 안되는거 보니까 refactoring 하면서 파일 삭제하고 새로 추가한거 때문에 그러는거 같은데 잘 모르겠네

2022-03-04 12:01 UTC, rapidrabbit76 requested changes
- 모델 생성 함수에 변경되는 인자 전부 제거 
- 이름은 정해져 있는데 인자에 따라서 변경 된다는게 이상함 
- else 가능한 제거 
- 하드코딩 밖은거 가능한 밖으로 빼기

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/MobileNetV1/blocks.py
> +            nn.ReLU()
inplace 안쓰고?

2022-03-04 12:01 UTC, rapidrabbit76 commented on main.py
> +    "LitGoogLeNet": LitGoogLeNet,
LitGoogLeNet -> GoogleLeNet

2022-03-04 12:01 UTC, rapidrabbit76 commented on main.py
> +    "LitGoogLeNet": LitGoogLeNet,
LitGoogLeNet -> GoogleLeNet

2022-03-04 12:01 UTC, rapidrabbit76 commented on main.py
> +    "LitResNet": LitResNet,
LitResNet -> ResNet

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/blocks.py
> +            layers.append(nn.ReLU())
inplace 일부러 안쓰는거?

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/lightning_model.py
> +            'scheduler': ReduceLROnPlateau(
ReduceLROnPlateau 엄청 좋아하네 효과적이던가? patience 어느정도 주고 쓰고 있어 ?

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/lightning_model.py
> +                mode='min',
mode 도 인자로 빼버리자

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/lightning_model.py
> +                mode='min',
mode 도 인자로 빼버리자

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/lightning_model.py
> +                mode='min',
mode 도 인자로 빼버리자

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/models.py
> +        model_type: str = '18',
model_type 인자 빼버리자 
저 값 바꾸면 ResNet_18 이 아니잖아 
혼란스러워질듯

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/ResNet/models.py
> +    def __init__(
생성자 인자 model_type을 제일 위로 

type
image_channels
num_classes 

순으로

2022-03-04 12:01 UTC, rapidrabbit76 commented on main.py
> +    "LitAlexNet": LitAlexNet,
rm : LIt

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/EfficientNetV1/models.py
>          model_type: str = 'b0',
이거도 동일하게 type 은 인자에서 빼버리자

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/MobileNetV1/models.py
>          alpha: float = 1.0,
변경되는 수치 전부다 빼버리자 

대문자로 수정 해주고

2022-03-04 12:01 UTC, rapidrabbit76 commented on main.py
> +    "AlexNet": LitAlexNet,
좋아!

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/MobileNetV2/models.py
> +        alpha: float = 1.0,
변경되는 인자는 전부 제거

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/MNASNet/blocks.py
> +        else:
else 가능한 전부 제거

2022-03-04 12:01 UTC, rapidrabbit76 commented on models/MNASNet/models.py
> +        alpha: float = 0.5,
여기도 변경되는 인자 전부 제거

2022-03-04 13:00 UTC, zkdlfrlwl2 commented on models/MobileNetV1/blocks.py
> +            nn.ReLU()
그게 뭐하는거야 ?

2022-03-04 13:01 UTC, zkdlfrlwl2 commented on main.py
> +    "LitGoogLeNet": LitGoogLeNet,
아 ㅇㅇ 이거는 변경 안되어있었네 바로 수정할게

2022-03-04 13:02 UTC, zkdlfrlwl2 commented on main.py
> +    "LitGoogLeNet": LitGoogLeNet,
![image](https://user-images.githubusercontent.com/92927837/156768173-020e76e3-a21f-4a6b-8706-f9d7133c9eaf.png)
내거엔 변경되어있는데 뭐지

2022-03-04 13:04 UTC, zkdlfrlwl2 commented on models/ResNet/lightning_model.py
> +            'scheduler': ReduceLROnPlateau(
그냥 대회하면서 스케쥴러 주는게 습관되서 쓰는거긴한데. 가장 무난한게 Plateau 이거라서 쓰는 중. 이미지 fine tuning 할 때는 cosine annealing 주로 사용함

2022-03-04 13:04 UTC, zkdlfrlwl2 commented on models/ResNet/lightning_model.py
> +                mode='min',
오케

2022-03-04 13:05 UTC, zkdlfrlwl2 commented on models/ResNet/models.py
> +        model_type: str = '18',
이 메소드에서만 빼자는거지 ?

2022-03-04 13:06 UTC, zkdlfrlwl2 commented on models/ResNet/models.py
> +    def __init__(
오케

2022-03-04 13:06 UTC, zkdlfrlwl2 commented on models/EfficientNetV1/models.py
>          model_type: str = 'b0',
오케

2022-03-04 13:07 UTC, zkdlfrlwl2 commented on models/MobileNetV1/models.py
>          alpha: float = 1.0,
![image](https://user-images.githubusercontent.com/92927837/156768856-e7da6cde-807c-4746-b8da-7623fe91c56d.png)
내 branch에서는 대문자로 되어있는데 이상하네

2022-03-04 13:40 UTC, rapidrabbit76 commented on main.py
> +    "LitGoogLeNet": LitGoogLeNet,
이전 커밋 기록 부터 봐서 그런듯 ㅇㅇ

2022-03-04 13:41 UTC, rapidrabbit76 commented on models/MobileNetV1/models.py
>          alpha: float = 1.0,
alpha: float = 1.0 이런거 없에 버려줘

2022-03-04 13:43 UTC, rapidrabbit76 commented on models/ResNet/lightning_model.py
> +            'scheduler': ReduceLROnPlateau(
cosine GAN에서 한번 써보고 바로 봉인했는데.. ㅠㅠ

2022-03-04 13:43 UTC, zkdlfrlwl2 commented on models/ResNet/lightning_model.py
> +            'scheduler': ReduceLROnPlateau(
스케쥴러도 잘 사용하면 성능 쥐어짜는데 도움 되더라고 ㅇㅇ

2022-03-04 13:44 UTC, rapidrabbit76 commented on models/ResNet/models.py
> +        model_type: str = '18',
함수로 빼놓은건 그 모델로 강제하려고 하는건데 
저런식으로 만들면 ResNet_18에서 model_type만 다른거 주면 바뀔수있잖아 
그런 실수를 아에 방지해버리려고 타입 줄꺼면 class 호출해라는거지

2022-03-04 13:47 UTC, rapidrabbit76 commented on models/MobileNetV1/blocks.py
> +            nn.ReLU()
내부 복사안하고 입력된 텐서를 직접 수정하는 방식 
https://discuss.pytorch.org/t/what-is-in-place-operation/16244

2022-03-04 14:03 UTC, zkdlfrlwl2 commented on models/MobileNetV1/blocks.py
> +            nn.ReLU()
저 inplace 인자가 ReLU 말고도 있네 ? Activation에는 다 적용 가능하게 해놓은건가

2022-03-05 06:02 UTC, rapidrabbit76 requested changes

2022-03-05 06:02 UTC, rapidrabbit76 commented on models/MobileNetV3/models.py
> +def MobileNetV3_small(
작은거를 위로 

그리고 
model_type: str = 'large',
이거 없에버리고 

MobileNetV3(image_channels, num_classes, alpha, "large", dropout_rate)

처럼 고정해줘 안 그러면 large 인데 model_type 바꾸면 다른 걸로 되버리니깐 혼란스럽다.

2022-03-05 06:02 UTC, rapidrabbit76 commented on models/MobileNetV2/models.py
> +        alpha: float = 0.75,
alpha 삭제

2022-03-05 06:02 UTC, rapidrabbit76 commented on models/MobileNetV2/models.py
> +        alpha: float = 0.5,
alpha 삭제

2022-03-05 06:16 UTC, rapidrabbit76 reviewed
좋다 문제는 없어 보이네 
다음 부턴 conversation 을 남겨줘 
다음 작업 진행할게요!

2022-03-05 06:29 UTC, rapidrabbit76 reviewed
ㅇㅋㅇㅋ!

2022-03-05 06:31 UTC, rapidrabbit76 approved these changes

2022-03-05 06:31 UTC, merged