Pytest Github Actions 적용한 branch PR
rapidrabbit76/Classification-For-Everyone pull request #22
Opened 2022-03-11 13:12 UTC by zkdlfrlwl2

# Summary

push trigger로 pytest 자동으로 돌아가는 github actions 적용

# Work

코드 수정 후 push 하면 github actions이 자동으로 pytest tests/ 돌려주게 만듬
처음 해본거라 리뷰 해보고 보완할 사항 있으면 코멘트 바람

# Related issues

[관련 이슈](https://github.com/rapidrabbit76/Classification-For-Everyone/issues/18)

2022-03-11 13:57 UTC, rapidrabbit76 commented on tests/EfficientNetV1/conftest.py
> +        EfficientNet_b7,
누락 되어 있었나???

2022-03-11 14:10 UTC, zkdlfrlwl2 commented on tests/EfficientNetV1/conftest.py
> +        EfficientNet_b7,
@rapidrabbit76 예스!

2022-03-20 04:23 UTC, rapidrabbit76 commented
PR 확인해줘 ㅠㅠ

2022-03-20 10:15 UTC, zkdlfrlwl2 commented
아 나는 니가 확인하고 코멘트 달아주는 줄 알고 기다리고 있었는데

2022-03-20 11:03 UTC, rapidrabbit76 requested changes

2022-03-20 11:03 UTC, rapidrabbit76 commented on requirements.txt
> +numpy
어어... 이러지 말고 버전을 명시해줘

numpy는 pytorch 받을때 의존성 있어서 알아서 받을듯

2022-03-20 11:03 UTC, rapidrabbit76 commented on .github/workflows/pytest.yaml
> +          pip install -r requirements.txt
`if [ -f requirements.txt ]; then pip install -r requirements.txt; fi`

파일 있어야 실행하는 방식으로 변경

2022-03-20 11:03 UTC, rapidrabbit76 commented on transforms/medium.py
> +class BaseTransforms:
Class Name 변경

2022-03-20 11:03 UTC, rapidrabbit76 commented on .github/workflows/pytest.yaml
> +          pip install -r requirements2.txt
?????

2022-03-20 11:03 UTC, rapidrabbit76 commented on .github/workflows/pytest.yaml
> +          pip install -r requirements2.txt
왜 2야

2022-03-21 06:30 UTC, zkdlfrlwl2 commented on transforms/medium.py
> +class BaseTransforms:
변경 확인

2022-03-21 12:24 UTC, zkdlfrlwl2 commented on requirements.txt
> +numpy
수정 완료

2022-03-21 12:24 UTC, zkdlfrlwl2 commented on .github/workflows/pytest.yaml
> +          pip install -r requirements.txt
수정 완료

2022-03-21 12:33 UTC, zkdlfrlwl2 commented on .github/workflows/pytest.yaml
> +          pip install -r requirements2.txt
테스트 하느라.. ㅎ 지금은 지움

2022-03-24 14:24 UTC, merged