PR ResNet
rapidrabbit76/Classification-For-Everyone pull request #3
Opened 2022-01-28 12:43 UTC by zkdlfrlwl2

First PR ResNet

2022-01-29 09:22 UTC, rapidrabbit76 requested changes
분기는 괜찮은데 
모델 구조 하드코딩은 변경 부탁

2022-01-29 09:22 UTC, rapidrabbit76 commented on ResNet/model/block.py
> +        if self.is_first_layer is True and self.is_first_block is True:
가급적이면 forward path 에서 분기 나누기 말것

2022-01-29 09:22 UTC, rapidrabbit76 commented on ResNet/model/model.py
> +        dim = 64
dim 변수 생성자에서 받아서 사용 하도록 변경 
이런거 하드코딩 하면 나중에 힘듬

2022-01-30 00:33 UTC, zkdlfrlwl2 commented on ResNet/model/model.py
> +        dim = 64
접수

2022-01-30 00:38 UTC, zkdlfrlwl2 commented on ResNet/model/block.py
> +        if self.is_first_layer is True and self.is_first_block is True:
모델 구조를 따로 make_layer method로 만들어라고 ? 그래서 그 method 통해서 만들어진 layer를 그대로 forward에서 사용하는 식으로 ?

2022-01-30 00:41 UTC, zkdlfrlwl2 commented on ResNet/model/block.py
> +        if self.is_first_layer is True and self.is_first_block is True:
forward 분기를 생성자 쪽으로 올려서 바꾸라는 말인가 ?

2022-01-30 06:28 UTC, rapidrabbit76 commented on ResNet/model/block.py
> +        if self.is_first_layer is True and self.is_first_block is True:
가능하면? 
어쩔수 없으면 분기는 괜찮아

2022-01-31 10:14 UTC, merged