PR MobileNetV1
rapidrabbit76/Classification-For-Everyone pull request #4
Opened 2022-02-03 13:44 UTC by zkdlfrlwl2

First PR

2022-02-03 14:57 UTC, rapidrabbit76 requested changes

2022-02-03 14:57 UTC, rapidrabbit76 commented on MobileNetV1/config.yaml
> +seed: '2022'
seed str value 사용 가능하나??

2022-02-03 14:57 UTC, rapidrabbit76 commented on MobileNetV1/model/block.py
> +            dim: list,
list -> List[int]

2022-02-03 14:57 UTC, rapidrabbit76 commented on MobileNetV1/model/block.py
> +        self.blocks = nn.Sequential(*layers)
list 넣는 방식 좋아하네

2022-02-03 14:57 UTC, rapidrabbit76 commented on MobileNetV1/model/block.py
> +        self.blocks = nn.Sequential(*layers)
난 그냥 identity 로 퉁처버리는 경우가 많은데

2022-02-03 14:57 UTC, rapidrabbit76 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
self.save_hyperparameters() 하면 다 보관 되는거 아님 ??

2022-02-03 23:55 UTC, zkdlfrlwl2 commented on MobileNetV1/model/block.py
> +            dim: list,
접수

2022-02-04 00:02 UTC, zkdlfrlwl2 commented on MobileNetV1/config.yaml
> +seed: '2022'
lightning 코드 까보니까 seed가 int type이 아니면 seed = int(seed) 이렇게 형 변환을 자체적으로 해주네 

`
elif not isinstance(seed, int):
    seed = int(seed)
`

2022-02-04 00:07 UTC, zkdlfrlwl2 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
wandb_logger.experiment.config.update(hparams) < 이 부분 말하는거가 ? 내가 디버깅 했을 때 self 확인해보니까 생성자에 self.save_hyperparameters() 넣어서 저장되는 건 생성자에서 입력으로 받는 파라미터만 저장되는 것 같던데 예를 들면 여기서 저장되는 건 image_channels, n_classes, lr, alpha 라는 소리

2022-02-04 00:08 UTC, zkdlfrlwl2 commented on MobileNetV1/model/block.py
> +        self.blocks = nn.Sequential(*layers)
저기서 어떻게 identity로 퉁침 ?

2022-02-04 00:23 UTC, zkdlfrlwl2 commented on MobileNetV1/model/block.py
> +        self.blocks = nn.Sequential(*layers)
list로 layer 쌓으니까 깔끔한 느낌이 들어서

2022-02-04 01:56 UTC, zkdlfrlwl2 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
그리고 저 self.save_hyperparameters()로 저장되는게 자동적으로 wandb에 logging 되는지는 모르겠다 ? logging 되려면 저렇게 wandb_logger.experiment.config.update(hparams)를 따로 명시해줘야 하는거 아닌감 ?

2022-02-04 05:17 UTC, rapidrabbit76 commented on MobileNetV1/config.yaml
> +seed: '2022'
맞네 당연히 인트 넣어야라고 생각했었음

2022-02-04 05:21 UTC, rapidrabbit76 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
아 맞제 config yaml 구조 바꿔야 할거같다. 
내부에 hparams 하나 더 놓는게 명확할거 같다고 생각했는데 돌리다 보니깐 아닌거 같더라고 ...

2022-02-04 06:14 UTC, zkdlfrlwl2 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
모델 생성자에 던져줘야하는 parameter하고 wandb에 따로 logging할 hyper parameter 이렇게 나눠서 config.yaml에 작성하면 될 것 같은데

2022-02-04 06:15 UTC, zkdlfrlwl2 commented on MobileNetV1/config.yaml
> +seed: '2022'
이런거 보면 라이브러리가 참 친절해 ㅋㅋ

2022-02-04 11:25 UTC, rapidrabbit76 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
> 모델 생성자에 던져줘야하는 parameter하고 wandb에 따로 logging할 hyper parameter 이렇게 나눠서 config.yaml에 작성하면 될 것 같은데

싫어 이러면 두개 관리해야해서 싫다 ...

2022-02-04 14:18 UTC, zkdlfrlwl2 commented on MobileNetV1/train.py
> +    wandb_logger.experiment.config.update(hparams)
wandb table 보면 싹다 저장되는 것 같긴한데 어느 파트가 저장되는 건지는 좀 애매하네

2022-02-04 14:31 UTC, zkdlfrlwl2 commented
이런 PR 진행 중에 merge 하면 이것까지 포함되버리네 ㅋㅋ

2022-02-05 10:47 UTC, rapidrabbit76 commented on MobileNetV1/config.yaml
> +seed: '2022'
issue #5  확인

2022-02-05 10:53 UTC, rapidrabbit76 reviewed
merge MobileNet

2022-02-05 10:53 UTC, merged