MobileNetV3 PR
rapidrabbit76/Classification-For-Everyone pull request #6
Opened 2022-02-09 12:52 UTC by zkdlfrlwl2

MobileNetV3 PR & MobileNetV2 hyper-parameter tuning

2022-02-09 13:27 UTC, rapidrabbit76 requested changes

2022-02-09 13:27 UTC, rapidrabbit76 commented on MobileNetV3/datamodule/datamodule.py
> +                np.int16(np.round(rho*image_size)),
왜 int 16?

2022-02-09 13:27 UTC, rapidrabbit76 commented on MobileNetV3/model/model.py
> +            model_type = [
이부분들 class 밖으로 빼서 다시

2022-02-09 13:27 UTC, rapidrabbit76 commented on MobileNetV3/model/model.py
> +        if model_size == '_large':
왜 "_" 붙이는거?

2022-02-09 13:27 UTC, rapidrabbit76 commented on MobileNetV3/model/model.py
> +            model_type = [
dict로 하자

2022-02-09 13:59 UTC, zkdlfrlwl2 commented on MobileNetV3/datamodule/datamodule.py
> +                np.int16(np.round(rho*image_size)),
사이즈 줄이려고

2022-02-09 14:01 UTC, zkdlfrlwl2 commented on MobileNetV3/model/model.py
> +        if model_size == '_large':
모델 저장할 때 모델 이름을 config.project_name+config.model_size 이렇게 넘겨주는데 저 사이에 +'_'+ 넣기 싫어서

2022-02-09 14:03 UTC, zkdlfrlwl2 commented on MobileNetV3/model/model.py
> +            model_type = [
List의 hash 값을 만들어서 key로 ? 검색 좀 해봐야겠구만

2022-02-10 00:06 UTC, zkdlfrlwl2 commented on MobileNetV3/model/model.py
> +            model_type = [
class 밖으로 빼서 dict로 만드는 이유가 뭐임 ??

2022-02-10 14:09 UTC, rapidrabbit76 commented on MobileNetV3/model/model.py
> +            model_type = [
외부에서 주입하는 방식으로 짜려고 해서 
난 그게 더 좋더라고 class안을 복잡하게 만드는게 싫어

2022-02-10 14:10 UTC, rapidrabbit76 commented on MobileNetV3/model/model.py
> +        if model_size == '_large':
음 ... ㅇㅋ

2022-02-10 15:22 UTC, zkdlfrlwl2 commented
list -> dict으로 바꿧는데 확인 좀 ㅎ

2022-02-11 00:20 UTC, zkdlfrlwl2 commented
오늘 출근하기 전에 잠깐 확인해보니까 model save할 때, torch script에서 뭔가 Error 뱉던데 퇴근하고 확인 좀 해봐야할 듯

2022-02-11 12:47 UTC, rapidrabbit76 commented
> 오늘 출근하기 전에 잠깐 확인해보니까 model save할 때, torch script에서 뭔가 Error 뱉던데 퇴근하고 확인 좀 해봐야할 듯

save 쪽은 리펙토링 할때 한번에 하자 지금은 빠르게 구현

2022-02-11 12:49 UTC, rapidrabbit76 reviewed
refactor: model type to dict

2022-02-11 12:49 UTC, merged